### ISSUE TITLE
Downloaded csv has no data

### ISSUE THREAD

**Issue by wheresmyjetpack22** [zedxter/DataTablesCSV#1]
The csv does not seem to contain any of the data from the table. 
Here's the code I'm testing with:

`<html lang="en">
  <head>
      <meta charset="utf-8">
      <title>jQuery Data Table</title>
        <link rel="stylesheet" type="text/css" href="/table_tools_project/jquery.dataTables.css">
        <script type="text/javascript" charset="utf8" src="/table_tools_project/jquery.js"></script>
        <script type="text/javascript" charset="utf8" src="/table_tools_project/jquery.dataTables.js"></script>
        <link rel="stylesheet" type="text/css" href="/table_tools_project/dataTables.CSV.css">
        <script type="text/javascript" charset="utf8" src="/table_tools_project/dataTables.CSV.js"></script>
    <script>
        $(document).ready(function () {
            $('#table_id').DataTable({
            dom: 'Vlfrtip'
            });
        });
  </script>
  </head>
  <body>
   <table id="table_id" class="display">
    <thead>
        <tr>
            <th>Column 1</th>
            <th>Column 2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Row 1 Data 1</td>
            <td>Row 1 Data 2</td>
        </tr>
        <tr>
            <td>Row 2 Data 1</td>
            <td>Row 2 Data 2</td>
        </tr>
    </tbody>
</table>
</body>
</html>`

**Comment by zedxter** [comment]
Hello @wheresmyjetpack22, interesting. I use it with ajax-based datatables, will check it with your code soon.

**Comment by wheresmyjetpack22** [comment]
I appreciate it. I also commend you for writing a csv exporter for DataTables. The TableTools extension seems to be pretty lacking.

**Comment by williamsdb** [comment]
Hi, I get exactly the same thing, i.e. an empty file. However, I also get the same thing with the tabletools copy function too which says I have zero rows but there are nine shown.

For some reason the button also isn't rendering correctly. 

![pulseinconfidence_-_get_the_heartbeat_of_your_organisation](https://cloud.githubusercontent.com/assets/8099483/8543767/4de02564-2497-11e5-887f-ccbcddd82ec3.png)

**Comment by zedxter** [comment]
Hi guys. Please update sources and try it again.
